@ActivoFijoAPI_HostAddress = http://localhost:5268

GET {{ActivoFijoAPI_HostAddress}}/api/Documentacion/
Accept: application/json

###
GET {{ActivoFijoAPI_HostAddress}}/api/Departamentos/
Accept: application/json
