@ActivoFijoAPI_HostAddress = http://localhost:5268

GET {{ActivoFijoAPI_HostAddress}}/api/Documentacion/
Accept: application/json

###
GET {{ActivoFijoAPI_HostAddress}}/api/departamentos/
Accept: application/json

###
GET {{ActivoFijoAPI_HostAddress}}/api/departamentos/1
Accept: application/json

###
GET {{ActivoFijoAPI_HostAddress}}/api/empleados
Accept: application/json

###
GET {{ActivoFijoAPI_HostAddress}}/api/tiposActivos
Accept: application/json

###
GET {{ActivoFijoAPI_HostAddress}}/api/activosfijos
Accept: application/json